FROM oven/bun:1.2.2

WORKDIR /app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./package*.json ./
COPY ./apps/http-server/ ./apps/http-server/

RUN cd ./apps/http-server && bun install && cd ../..

RUN bun install
RUN bun run db:generate

EXPOSE 3001

CMD ["bun", "run", "start:backend"]