name: Deploy Backend server

on: 
  push: 
    branches: [ main ]

jobs: 
  build-and-push-docker-image:  # <- job ID
    runs-on: ubuntu-latest       # <- properly indented
    steps: 
      - name: Checkout the code 
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # fixed spacing
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
      - name: Deploy to Remote Server
        run: |
          echo "${{ secrets.MY_SSH_TODO }}" > ssh_key
          chmod 600 ssh_key

          # Optional: Clean up existing container
          ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 "docker stop user_backend || true && docker rm user_backend || true"

          # Run new container
          ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 \
            "docker run --name user_backend -d -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}"
