name: Deploy Backend
on: 
  push: 
    branches: [ main ]

jobs: 
  build-and-push-docker-image:
  runs-on: ubuntu-latest
  steps: 
    - name: checkout the code 
      uses: actions/checkout@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME }} # docker hub username
        password: ${{secrets.DOCKER_PASSWORD }} # docker hub password
    
    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile.backend
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/backend:${{github.sha}}