name: Deploy Frontend
on:
  push:
    branches: [main]
jobs:
  build-and-push-docker-image:
  runs-on: ubuntu-latest
  steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: docker login
      uses: docker/login-action@v2
      with: 
        username: ${{secrets.DOCKER_USERNAME }}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: build and push
      uses: docker/docker-build-action@v2
      with: 
        context: .
        file: docker/Dockerfile.frontend
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/frontend:${{github.sha}}
        build-args:
          - DATABASE_URL=${{secrets.DATABASE_URL}}
          
