name: Deploy Frontend server

on:
  push:
    branches: [main]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Deploy to Remote Server
        run: |
          echo "${{ secrets.MY_SSH_TODO }}" > ssh_key
          chmod 700 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 "sudo docker stop user_frontend || true && sudo docker rm user_frontend || true"
          ssh -o StrictHostKeyChecking=no -i ssh_key cocane@34.93.115.4 \
            "sudo docker run --name user_frontend -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}"
