name: Deploy Websocket server

on: 
  push: 
    branches: [ main ]

jobs: 
  build-and-push-docker-image:  # <- job ID
    runs-on: ubuntu-latest       # <- properly indented
    steps: 
      - name: Checkout the code 
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # fixed spacing
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/websocket:${{ github.sha }}
      - name: Deploy to the VM
        run:
          echo "${{ secrets.MY_SSH_TODO }}" > ~/ssh_key
          mkdir -p /home/ubuntu/.ssh
          chmod 700 /home/ubuntu/.ssh
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key cocane@34.93.115.4 -t "docker stop user_websocket && docker run --name user_websocket -d -p 3001:3001 cocane/websocket:${{ github.sha }}"
